all: functor LengthMismatch Thanksgiving

functor: functor.cpp functor.h
	g++ -g -Wall -std=c++11 -c functor.cpp -o functor.o

LengthMismatch:  LengthMismatch.cpp  LengthMismatch.h
	g++ -g -Wall -std=c++11 -c LengthMismatch.cpp -o LengthMismatch.o

Thanksgiving:  Thanksgiving.cpp
	g++ -g -Wall -std=c++11 -c Thanksgiving.cpp -o Thanksgiving.o

